### ISSUE TITLE
Nougat app installations from play store not working 

### ISSUE THREAD

**Issue by hoshsadiq** [ggsava/block-this#11]
I can't install any apps from the play store unless I switch this off.

**Comment by polojoe** [comment]
I can confirm this behavior.

**Comment by ggsava** [comment]
I will release a fix in the next few days. Any of you able to test it for me? I don't have an android 7 device to test with..

**Comment by polojoe** [comment]
of course

**Comment by hoshsadiq** [comment]
Happy to! It's a bit of a pain having to disable it just to install apps. Thanks for the quick response :)

**Comment by ggsava** [comment]
I will try to release a completely reworked version next week. With the issue fixed. Thanks.

**Comment by GoOtterGo** [comment]
Yeah, had to disable it, having the are issue. Also prevents updates to existing apps similarly. 

I also noticed new, occasional "can't connect" errors while very clearly connected to a WiFi network, but that's a separate issue, obviously.

**Comment by ggsava** [comment]
@GoOtterGo @hoshsadiq @polojoe I have prepared a beta version of the 3.0 release of Block This. Please check if your problem persists, or if you face any other problems with the new version.

You can download 3.0 beta at https://block-this.com/preview/block-this-3-beta.apk

**Comment by polojoe** [comment]
Playstore download and APP install works for me on lineageos 14.1 (Android 7.1.1)

**Comment by ggsava** [comment]
@polojoe, thanks! Glad to hear! I have a couple of more small things to fix and test before I release it officially, but it should be in the next day or two. This was the biggest issue and what most people complained about.

**Comment by GoOtterGo** [comment]
Play store seems to work again for me as well (Android 7.0)

**Comment by quorn23** [comment]
Hi @ggsava would it be possible to commit your changes to the dev branch here? :)

**Comment by ggsava** [comment]
@quorn23 Will do as soon as I can, I need to prepare the code for github (remove config files / passwords, etc) just haven't had the time yet. But soon you will see the complete code on github yes.

**Comment by ggsava** [comment]
By the way the app is now live and you should have gotten an update from the beta version. Please upgrade as the beta version might have some bugs still in there.

**Comment by ggsava** [comment]
@quorn23 done all changes are on github now
