### ISSUE TITLE
Reasoning behind adding multiple addresses 

### ISSUE THREAD

**Issue by Sirack** [ggsava/block-this#17]
Greetings,

What's the reason behind these lines? Wouldn't the first one work?

.addAddress("10.0.2.15", 24)
.addAddress("10.0.2.16", 24)
.addAddress("10.0.2.17", 24)
.addAddress("10.0.2.18", 24)

**Comment by ggsava** [comment]
Good question. I thought it should work with just one too, but some users experienced difficulties.. adding multiple addresses fixed it for them, but to be honest I'm not sure why or how.. 

One day I will get back to it and revise why it happens and what the correct settings are, I just used this as a quick fix as it worked right away.

**Comment by Sirack** [comment]
Okay. Thank you sir.
