### ISSUE TITLE
Exploring ideas for a new app icon

### ISSUE THREAD

**Issue by AdityaAnand1** [ggsava/block-this#2]
Just want to throw out a few ideas for the app icon..

![blockthisold](https://cloud.githubusercontent.com/assets/13274079/16299576/ac5478d0-3958-11e6-94ec-dd4dbe4c1c87.png)

Potential areas that could use another look:
* The Icon-to-Background size ratio is a bit off. The key is way too big. At a quick glance it almost doesn't even look like a key, but rather some abstract shape.
* There should either be a shadow or not. Right now, there's a hint of a shadow which is only visible when you look very closely. If we're gonna go down that road (having a shadow), it should be well defined. Or not at all, nothing wrong with a flat icon. Going either way would be better than the current icon.
* The color is nice. Down the line, we'd want to reinforce the same color throughout the app. I think the current color (#c55b5b) used in the logo will make a good primary color when we hopefully move to using material design.

Threw together some rough ideas:

Solid Shadow:
![ic_launcher](https://cloud.githubusercontent.com/assets/13274079/16302225/91816694-3967-11e6-94b7-78b649764d5b.png)
Fading Shadow:
![ic_launcher](https://cloud.githubusercontent.com/assets/13274079/16302248/b5bd906e-3967-11e6-9996-22104a7c49c3.png)
No Shadow:
![ic_launcher](https://cloud.githubusercontent.com/assets/13274079/16302251/bdbc0688-3967-11e6-9ee2-a7260b229ec2.png)

What do you think?

**Comment by Tgo1014** [comment]
The fading one looks very nice

**Comment by ggsava** [comment]
I agree! I think the key with the fading shadow looks very nice. I'd will try it out to see how it looks on my phone but I think it will be great. Thanks a lot for doing this!

**Comment by stefpe** [comment]
I prefer the second one, looks nice!

**Comment by AdityaAnand1** [comment]
Haha! I was secretly hoping you like the fading one.

I'm still learning to github, but I put the different resolutions in [this](https://github.com/AdityaAnand1/BlockThis-Icon) repo of the second icon.

**Comment by ggsava** [comment]
It worked fine! Already merged into master!
