### ISSUE TITLE
Is it possible to block youtube ads?

### ISSUE THREAD

**Issue by Divran** [ggsava/block-this#30]
Hi

The main thing I would want out of this app is to block youtube's video ads. Is this possible? I know most desktop PC browser adblockers successfully do it, but maybe it's not possible on an unrooted android.

**Comment by Brains** [comment]
I am suffering from `YouTube` ads too. Is it possible?
Maybe I can even help, just point me in the right direction somebody, please.

**Comment by Brains** [comment]
By the way, can't open [Forum](https://forum.block-this.com/)

![image](https://user-images.githubusercontent.com/5301844/48478835-20117000-e80e-11e8-928e-d1b48926b6c7.png)

**Comment by pwuk** [comment]
NewPipe is an alternative (available on FDroid)

**Comment by Divran** [comment]
Indeed, I found out those existed after creating this issue. Thanks, though.

I think this can be closed now since it seems to not be possible for a non rooted device to adblock the default YouTube app. As you say, other unofficial YouTube apps can still do it.

**Comment by Brains** [comment]
I use `Blokada`, it blocks all ads inside and before videos, only static ad banner below video is left.
It's also open-source `VPN` service
