### ISSUE TITLE
Following best practices...

### ISSUE THREAD

**Issue by AdityaAnand1** [ggsava/block-this#4]
So many things...

Java:
- Use [butterknife](http://jakewharton.github.io/butterknife/) to remove findViewById bloat. Will need to change all activities a little bit
- Use [LeakCanary](https://github.com/square/leakcanary) to make sure there are no leaks. (This just needs one method call in the Application class.)
- Use [Hugo](https://github.com/JakeWharton/hugo) for automatic logging
- Use [Timber](https://github.com/JakeWharton/timber) as a better alternative to Log.v(...) .No need to define our own custom TAGs and we shouldn't be calling logging methods in the release build.

The above are just developer candy, no change will be perceived by the users.

And then there's the UI:
- The app uses holo theme. _Oh my god_. Need to upgrade to material.
- Use [Material Dialogs](https://github.com/afollestad/material-dialogs)
- No need to go back to TeaserActivity in onBackPressed(). User has already seen it so there's no need to show it again. The best scenario would be just one screen, where we can turn the blocker on/off, along with a button that shows a dialog (that's automatically shown only on the first time. This is where your teaserActivity stuff will go)
- Actually following material design would mean a complete redesign of the entire app from the ground up.

And we need to update gradle version, targetSdk, library versions etc. And there's so much more. My point is, there's a lot to be done and I'd like to get started on all of these. 

I'll do the Java things first since it'll be quicker, then I'll work on the UI. Hopefully I'll be back with some screenies in a few hours.

**Comment by ggsava** [comment]
I have to work during the day (got a day job) but if I can help with something just let me know. Otherwise all great suggestions.. Android is not really my thing so I prefer to listen to people with experience (people like you). Thanks again.

**Comment by AdityaAnand1** [comment]
How does this look?

![device-2016-06-24-234528](https://cloud.githubusercontent.com/assets/13274079/16346558/900b0438-3a65-11e6-80d1-9d6c35bfecfe.png)

Went with a clean and minimalist look. Will add a share icon in the toolbar as well so that users can share the URL of Block This.

The APK is always available on the same URL right? Like, right now it's at: `https://block-this.com/block-this-latest.apk `
I just want to confirm whether the latest APKs will always be available on this URL. Why? I think we should put a QR code inside the app. The user opens the QR code image, their friend scans it and can then easily install the app. We are trying to survive outside the play store after all. This will neatly fit inside a side navigation drawer menu item.

But for now, I'll just finalize the UI, version updates, replace old stuff with new stuff and send a pull request. I'll send you the modified APK before so you can confirm whether all the functions are still there.  Then we can think of more stuff to add, maybe take a look at competitors see what they are doing.

**Comment by ggsava** [comment]
@AdityaAnand1 Sorry I have been very busy in the last week and did not have any time to look at github. It looks very nice in my opinion. The APK is always available at this link yes. The idea with QR code is pretty good, and share buttons as well. 

I'm not sure if the Play button shouldn't be just a slight bit larger? We can also work on the text i'm not sure "feel the freedom" is the best slogan here :D It was just something I put up there quickly. What do you think?

**Comment by JakeChampion** [comment]
#7 will help resolve the distribution issue you mentioned at https://github.com/ggsava/block-this/issues/4#issuecomment-228424120

An app which has a similar interaction model is Orbot, perhaps you can take some design inspiration from what they have done. Namely making the start/stop button take up most of the screen real estate as @ggsava mentioned in the comment above this.
