### ISSUE TITLE
Distribution request: add to F-Droid

### ISSUE THREAD

**Issue by JakeChampion** [ggsava/block-this#7]
F-Droid is an FOSS alternative to the Play Store, having your application in their should help people install it on their devices and stay up to date. Here is the link to the [submission-queue](https://f-droid.org/forums/forum/submission-queue/)

**Comment by ggsava** [comment]
At the moment there is no plan for distributing Block This over F-Droid because of signature problems. I would have to throw away all the users the app currently has to distribute over F-Droid.

**Comment by JakeChampion** [comment]
Why would you have to throw away all the users currently using the app?

**Comment by ggsava** [comment]
@JakeChampion F-Droid takes the source code and builds the app with a new signature. Which means, users who already have the app with the old signature cannot update it to the app delivered by F-Droid. 

I will have to somehow make the users to remove the old app completely and go to F-Droid to download it again. It makes it really difficult to keep the users the app already has..

**Comment by ggsava** [comment]
What makes it worse is that, in case the signatures of the old and new version don't match, Android shows totally unhelpful error message to the user "Application could not be updated" .

**Comment by IzzySoft** [comment]
@ggsava as a compromise: May I suggest you then add the `.apk` here at Github, best to the `releases/` page (see: [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help)? I could then automatically fetch it to [my F-Droid compatible repo](https://android.izzysoft.de/repo) (including updates within ~24h after your adding the new release with an `.apk` attached). That way it would keep your signature – but could still be installed (and kept up-to-date) using the F-Droid client by simply adding that repo to it. Multiple projects here at Github already use that, so the repo holds almost 250 apps as of today.

**Comment by ggsava** [comment]
@IzzySoft Good idea! I wasn't aware that this is possible as I'm not very familiar with F-Droid. I will look into it and make it available as soon as I can. Thx.

**Comment by IzzySoft** [comment]
Great, thanks! Simply update this issue (I'm subscribed, so I get a note then) when the `.apk` is available that way, and I'll set it up ASAP and let you know the link (in case you want to place it e.g. in the `README.md` so people find it :smile_cat: ) Thumbs up meanwhile!

**Comment by ggsava** [comment]
@IzzySoft I just added a release. Feel free to use it if you wish. Thx.

**Comment by IzzySoft** [comment]
Thanks, @ggsava ! But may I ask you two things: 1) please attach the `.apk` as `.apk` for future releases (not zipped); that's how other projects do it and only that way my auto-updater will find future versions automatically. 2) please take care that the `versionName` matches the tag (I'm pretty sure you already take care to always increase `versionCode` for each subsequent release :smile_cat: ).

You can now find the `.apk` [here](https://apt.izzysoft.de/fdroid/index/apk/com.savageorgiev.blockthis). Feel free to point to that place so people can install your app, stay informed about updates and easily apply them using the F-Droid client. A big :+1: and keep up the good work!

**Comment by ggsava** [comment]
@IzzySoft sure I can include the actual build version. How do others attach .apk to it? Github didnt allow me to add an .apk file as an upload very strange..

**Comment by IzzySoft** [comment]
Cool! Then let's see how the next automatic update works :)

Uh, looking at the `releases/` page I'm confused – guess you understood me wrong. The *tag* (`3.0.1`) was fine. It was the `versionName` in the `.apk` file that didn't match the tag (`versionName=3.0`). Keep with the tags as before, just make sure the APK reflects that :)

If you want some other repos for cross-checking:

* https://github.com/k0shk0sh/FastHub/releases
* https://github.com/henrichg/PhoneProfilesPlus/releases
* https://github.com/arunkumar9t2/chromer/releases
